apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: dev
        version: 0be592b0466ca3e2cd343e632c3d0ecd87a409db-1652187971
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:883c5690927948f1ead8a2d00760a48ceef4dfaa906f90b130bb3397843d7365
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: slackbot
        name: slackbot
        phase: dev
        version: 0be592b0466ca3e2cd343e632c3d0ecd87a409db-1652187971
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_ENCRYPTIONSERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_ENCRYPTION_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_DATABASESERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DATABASE_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_HOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_HOST
              name: test-secret
        - name: PASSWORDEXCHANGE_DBHOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DBHOST
              name: test-secret
        - name: OAUTHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_PASSWORD
              name: test-secret
        - name: OAUTHDB_USER
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_USER
              name: test-secret
        - name: OAUTHDB_NAME
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_NAME
              name: test-secret
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_SIGNING_SECRET
              name: test-secret
        - name: SLACK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_ID
              name: test-secret
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_SECRET
              name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:eb549af7ab00e2c5dfe2b8412dad714092f4dc75606f2ceb3ad7c7ab724f2d01
        name: slackbot
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: dev
        version: 0be592b0466ca3e2cd343e632c3d0ecd87a409db-1652187971
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:484bfc61cf0787423eb988dcf3a2247d63963feb0eaa8672657732981b16f7f2
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
      labels:
        app: database
        name: database
        phase: dev
        version: 0be592b0466ca3e2cd343e632c3d0ecd87a409db-1652187971
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:cddce74812b0631204fdc43bb4bb2dbb42c32be1ed59debc30ac6e024bf6fd5c
        name: database

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: slackbot-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: slackbot

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: dev

