apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: dev
        version: 143c9888d45f2d07a3b222e1aa27e4c4af0aeb74
    spec:
      containers:
      - args:
        - web
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:a15f59bfd7b88718cbaba6f5bc77d76953fc63fd971e5c21de88bcc1c95bc2e0
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: dev
        version: 143c9888d45f2d07a3b222e1aa27e4c4af0aeb74
    spec:
      containers:
      - args:
        - encryption
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:a15f59bfd7b88718cbaba6f5bc77d76953fc63fd971e5c21de88bcc1c95bc2e0
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
      labels:
        app: database
        name: database
        phase: dev
        version: 143c9888d45f2d07a3b222e1aa27e4c4af0aeb74
    spec:
      containers:
      - args:
        - database
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:a15f59bfd7b88718cbaba6f5bc77d76953fc63fd971e5c21de88bcc1c95bc2e0
        name: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: email
        name: email
        phase: dev
        version: 143c9888d45f2d07a3b222e1aa27e4c4af0aeb74
    spec:
      containers:
      - args:
        - email
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:a15f59bfd7b88718cbaba6f5bc77d76953fc63fd971e5c21de88bcc1c95bc2e0
        name: email
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: email-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: email
    phase: dev

