apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: dev
        version: 08ac35ed381f4270f7a8f4dec750b8f3f10cb525
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:199d31f7501f15a9f7f0b26985b3e68ec166793ed1d000f6e5574783c30132a5
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: slackbot
        name: slackbot
        phase: dev
        version: 08ac35ed381f4270f7a8f4dec750b8f3f10cb525
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_ENCRYPTIONSERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_ENCRYPTION_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_DATABASESERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DATABASE_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_HOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_PROD_HOST
              name: test-secret
        - name: PASSWORDEXCHANGE_DBHOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DBHOST
              name: test-secret
        - name: OAUTHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_PASSWORD
              name: test-secret
        - name: OAUTHDB_USER
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_USER
              name: test-secret
        - name: OAUTHDB_NAME
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_NAME
              name: test-secret
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_SIGNING_SECRET
              name: test-secret
        - name: SLACK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_ID
              name: test-secret
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_SECRET
              name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:4d7955e2bb4e74a137f9e8c49126d1cc89e483ac2055cfdd7fce9c08ab1081ff
        name: slackbot
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: dev
        version: 08ac35ed381f4270f7a8f4dec750b8f3f10cb525
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:5225eeb84f2b424593c9b5a14ecd91f70ffdbbbbc8ccef22f71de503887405e9
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
      labels:
        app: database
        name: database
        phase: dev
        version: 08ac35ed381f4270f7a8f4dec750b8f3f10cb525
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:0198526602800fe5c55b9bce77a0c75fd5c080c2f876425dc01551940d331c81
        name: database

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: slackbot-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: slackbot

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: dev

