apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: dev
        version: ad1fb09d4c36a3cc9fb9ffc9c7f1b3c166e99be8
    spec:
      containers:
      - args:
        - web
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:0dbc92ef2919b56fa488e058b66b05890995778ff6beafb325f6fae92944f61e
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: slackbot
        name: slackbot
        phase: dev
        version: ad1fb09d4c36a3cc9fb9ffc9c7f1b3c166e99be8
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_ENCRYPTIONSERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_ENCRYPTIONPRODSERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_DATABASESERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DATABASEPRODSERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_HOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_PRODHOST
              name: test-secret
        - name: PASSWORDEXCHANGE_DBHOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DBHOST
              name: test-secret
        - name: OAUTHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_PASSWORD
              name: test-secret
        - name: OAUTHDB_USER
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_USER
              name: test-secret
        - name: OAUTHDB_NAME
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_NAME
              name: test-secret
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_SIGNING_SECRET
              name: test-secret
        - name: SLACK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_ID
              name: test-secret
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_SECRET
              name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:dd0197098b7425a4eee7e59db152be7e1cf321c32281efd36c11a2267250bb63
        name: slackbot
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: encryption
        name: encryption
        phase: dev
        version: ad1fb09d4c36a3cc9fb9ffc9c7f1b3c166e99be8
    spec:
      containers:
      - args:
        - encryption
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:0dbc92ef2919b56fa488e058b66b05890995778ff6beafb325f6fae92944f61e
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: database
        name: database
        phase: dev
        version: ad1fb09d4c36a3cc9fb9ffc9c7f1b3c166e99be8
    spec:
      containers:
      - args:
        - database
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:0dbc92ef2919b56fa488e058b66b05890995778ff6beafb325f6fae92944f61e
        name: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: email
        name: email
        phase: dev
        version: ad1fb09d4c36a3cc9fb9ffc9c7f1b3c166e99be8
    spec:
      containers:
      - args:
        - email
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:0dbc92ef2919b56fa488e058b66b05890995778ff6beafb325f6fae92944f61e
        name: email
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: email-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: email
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: slackbot-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: slackbot

