apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: dev
        version: 4562bac3e84865291fd42184eb47d167b32da15e-1652032966
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:6c74b655d1f74c9064d244e55f078aa17800ef2f8120cbe9357a313f6fbfce36
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: slackbot
        name: slackbot
        phase: dev
        version: 4562bac3e84865291fd42184eb47d167b32da15e-1652032966
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_ENCRYPTION_PROD_SERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_ENCRYPTION_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_DATABASESERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DATABASE_PROD_SERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_HOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_HOST
              name: test-secret
        - name: PASSWORDEXCHANGE_DBHOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DBHOST
              name: test-secret
        - name: OAUTHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_PASSWORD
              name: test-secret
        - name: OAUTHDB_USER
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_USER
              name: test-secret
        - name: OAUTHDB_NAME
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_NAME
              name: test-secret
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_SIGNING_SECRET
              name: test-secret
        - name: SLACK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_ID
              name: test-secret
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_SECRET
              name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:f9e612acd96e60ec0c6e9d98338e3bea38b63ac6afda4c51f6f0ae6aa932ae04
        name: slackbot
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: dev
        version: 4562bac3e84865291fd42184eb47d167b32da15e-1652032966
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:d6043ad56e51e0b7d61a435547a69ef4707fac7e3250ad0ec2671628f006166d
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-dev-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
      labels:
        app: database
        name: database
        phase: dev
        version: 4562bac3e84865291fd42184eb47d167b32da15e-1652032966
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: dev
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:f6d90267513dcbea542267924d8f0a0caf0b681db5fb1d30c7263d5e7eee03ab
        name: database

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-dev-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: slackbot-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: slackbot

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-dev-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: dev

