apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-prod-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: prod
        version: v.0.2.1
    spec:
      containers:
      - args:
        - web
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: prod
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:0d13749c5d0beb489802af76182fa74a201a43669e4af2930ac72b3bc74d1713
        name: password-exchange
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: slackbot
        name: slackbot
        phase: prod
        version: v.0.2.1
    spec:
      containers:
      - env:
        - name: PASSWORDEXCHANGE_ENCRYPTIONSERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_ENCRYPTIONPRODSERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_DATABASESERVICE
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DATABASEPRODSERVICE
              name: test-secret
        - name: PASSWORDEXCHANGE_HOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_PRODHOST
              name: test-secret
        - name: PASSWORDEXCHANGE_DBHOST
          valueFrom:
            secretKeyRef:
              key: PASSWORDEXCHANGE_DBHOST
              name: test-secret
        - name: OAUTHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_PASSWORD
              name: test-secret
        - name: OAUTHDB_USER
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_USER
              name: test-secret
        - name: OAUTHDB_NAME
          valueFrom:
            secretKeyRef:
              key: OAUTHDB_NAME
              name: test-secret
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_SIGNING_SECRET
              name: test-secret
        - name: SLACK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_ID
              name: test-secret
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SLACK_CLIENT_SECRET
              name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:0da40fc8189c0e4cc872672a12d91af0026b6550d4ccc1c283a9170d3b5e98e3
        name: slackbot
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-prod-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: prod
        version: v.0.2.1
    spec:
      containers:
      - args:
        - encryption
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: prod
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption@sha256:0d13749c5d0beb489802af76182fa74a201a43669e4af2930ac72b3bc74d1713
        name: encryption

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-prod-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
        linkerd.io/inject: enabled
      labels:
        app: database
        name: database
        phase: prod
        version: v.0.2.1
    spec:
      containers:
      - args:
        - database
        env:
        - name: PASSWORDEXCHANGE_RUNNING_ENVIRONMENT
          value: prod
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database@sha256:0d13749c5d0beb489802af76182fa74a201a43669e4af2930ac72b3bc74d1713
        name: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email-prod-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: email
        name: email
        phase: prod
        version: v.0.2.1
    spec:
      containers:
      - args:
        - email
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: prod
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:0d13749c5d0beb489802af76182fa74a201a43669e4af2930ac72b3bc74d1713
        name: email
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: passwordexchange-prod-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: passwordexchange
    phase: prod

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: encryption-prod-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: encryption
    phase: prod

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: database-prod-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: database
    phase: prod

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: email-prod-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: email
    phase: prod

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  name: slackbot-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: slackbot

